=== juyuan-yang/IRrelated/nanoxml/inputs/sql-structure.dtd
<!--
TYPICAL INVOCATION:
#  <!DOCTYPE database SYSTEM "sql-structure.dtd">

PURPOSE:
  This is an XML dtd for defining the structure of a SQL database.

DEPENDENCIES:
  None.

CHANGE HISTORY:
  02 Oct 2000 - Added version tag under database tag
  30 May 2000 - Created

MAINTAINER:
  Kyle Smith
  Capitol College
  ksmith@capitol-college.edu
-->

<!-- ....................................................................... -->
<!-- Entities for common attributes ........................................ -->
<!-- ....................................................................... -->

<!--	Common attributes:
	Every element has an ID attribute (sometimes required,
	but usually optional) for links, and a Role attribute
	for extending the useful life of the DTD by allowing
	authors to make subclasses for any element. common.att;
	is for common attributes where the ID is optional, and
	common-idreq.att; is for common attributes where the
	ID is required. -->
<!ENTITY % common.att
	'id		ID		#IMPLIED
	role		NMTOKEN		#IMPLIED'>
<!ENTITY % common-idreq.att
	'id		ID		#IMPLIED
	role		NMTOKEN		#IMPLIED'>

<!-- ....................................................................... -->
<!-- Elements .............................................................. -->
<!-- ....................................................................... -->

<!--	This is the top-level container -->
<!ELEMENT database (name, description?, version?, table+)>


<!ELEMENT name (#PCDATA)>

<!ELEMENT description (#PCDATA)>

<!ELEMENT version (#PCDATA)>

<!ELEMENT table (name, description?, field+, index*)>

<!ELEMENT field (name, description?, type, length?, option*, default?)>

<!ELEMENT index (type, name?, column+, references?)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT length (#PCDATA)>

<!ELEMENT option (#PCDATA)>

<!ELEMENT default (#PCDATA)>

<!ELEMENT column (#PCDATA)>

<!ELEMENT references (#PCDATA)>

=== juyuan-yang/IRrelated/nanoxml/inputs/notablefields_sc_20.xml
<!DOCTYPE database SYSTEM "sql-structure.dtd">

<database>
  <name>foo</name>
  <description>A database for storing random stuff</description>
  <version>1.0</version>

  <table>
    <name>bar</name>
    <description>A table for storing random stuff</description>
  
    <index>
      <type>primary key</type>
      <column>bar_id</column>
    </index>
  </table>

</database>

=== juyuan-yang/IRrelated/nanoxml/inputs/nofieldnames_sc_16.xml
<!DOCTYPE database SYSTEM "sql-structure.dtd">

<database>
  <name>foo</name>
  <description>A database for storing random stuff</description>
  <version>1.0</version>

  <table>
    <name>bar</name>
    <description>A table for storing random stuff</description>
  
    <field>
      <description>unique identifier for each bar</description>
      <type>int</type>
      <option>not null</option>
      <option>auto_increment</option>
    </field>

    <field>
      <description>name for each bar</description>
      <type>varchar</type>
      <length>255</length>
      <option>not null</option>
    </field>

    <index>
      <type>primary key</type>
      <column>bar_id</column>
    </index>
  </table>

</database>
